# Generated by Django 5.2.7 on 2025-10-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_fsm_ticket', '0005_auto_20250310_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_fsm_ticket.ticket')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_fsm_ticket.ticket',),
        ),
    ]
