# Generated by Django 5.2.7 on 2025-10-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_ticket', '0005_auto_20250310_1235'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicketUpdate',
            fields=[
                ('ticketupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_fsm_ticket.ticketupdate')),
                ('price', models.FloatField()),
                ('seller', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_fsm_ticket.ticketupdate',),
        ),
    ]
