# Generated by Django 5.2.7 on 2025-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_orderticketupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseticket',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
