# Generated by Django 3.2.9 on 2022-07-11 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketupdate',
            name='ts',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
