# Generated by Django 5.0.6 on 2024-05-14 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fsm_ticket", "0003_alter_ticket_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentTicketUpdate",
            fields=[
                (
                    "ticketupdate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_fsm_ticket.ticketupdate",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Attachment"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("django_fsm_ticket.ticketupdate",),
        ),
        migrations.CreateModel(
            name="DeleteAttachmentTicketUpdate",
            fields=[
                (
                    "ticketupdate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_fsm_ticket.ticketupdate",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_fsm_ticket.attachmentticketupdate",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("django_fsm_ticket.ticketupdate",),
        ),
    ]
