# Generated by Django 3.2.25 on 2025-03-10 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_ticket', '0004_attachmentticketupdate_deleteattachmentticketupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='ts',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
