# Generated by Django 5.2.10 on 2026-02-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_fsm_ticket", "0005_auto_20250310_1235"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmentticketupdate",
            options={},
        ),
        migrations.AlterModelOptions(
            name="deleteattachmentticketupdate",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticketupdate",
            options={},
        ),
    ]
