# Generated by Django 5.2.10 on 2026-03-31 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fsm_ticket", "0006_alter_attachmentticketupdate_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachmentticketupdate",
            name="uuid",
        ),
        migrations.AddField(
            model_name="ticket",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="ticketupdate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
