# Generated by Django 5.2.10 on 2026-03-31 08:20

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Ticket = apps.get_model("django_fsm_ticket", "Ticket")
    TicketUpdate = apps.get_model("django_fsm_ticket", "TicketUpdate")
    for row in Ticket.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    for row in TicketUpdate.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_fsm_ticket",
            "0007_remove_attachmentticketupdate_uuid_ticket_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]