# Generated by Django 5.2.10 on 2026-03-31 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_fsm_ticket", "0008_auto_20260331_0820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="ticketupdate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

    ]
