# Generated by Django 3.2.25 on 2025-04-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_fsm_ticket', '0005_auto_20250310_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicketUpdate',
            fields=[
                ('ticketupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_fsm_ticket.ticketupdate')),
                ('price', models.FloatField()),
                ('seller', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_fsm_ticket.ticketupdate',),
        ),
        migrations.CreateModel(
            name='PurchaseTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_fsm_ticket.ticket')),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_fsm_ticket.ticket',),
        ),
    ]
